### ISSUE TITLE
lein figwheel on 0.5 appears unable to find cljs/analyzer__init.class

### ISSUE THREAD

**Issue by cddr** [bhauman/lein-figwheel#285]
Running `lein figwheel` on a project freshly generated from `lein new figwheel foo`, crashes because it's unable to find cljs/analyzer__init.class.

#### Steps to reproduce:
```
rm -r ~/.m2/repositories/*
lein new figwheel yolo
cd yolo && lein figwheel
```
#### Expected:
To see the figwheel server running

#### Actual:
```
$ lein figwheel
clojure.lang.Compiler$CompilerException: java.io.FileNotFoundException: Could not locate cljs/analyzer__init.class or cljs/analyzer.clj on classpath: , compiling:(figwheel_sidecar/utils.clj:1:1)
 at clojure.lang.Compiler.load (Compiler.java:7142)
    clojure.lang.RT.loadResourceScript (RT.java:370)
    clojure.lang.RT.loadResourceScript (RT.java:361)
    clojure.lang.RT.load (RT.java:440)
    clojure.lang.RT.load (RT.java:411)
    ...
```

**Comment by cddr** [comment]
In case it helps, here is the output of `lein deps :tree`. I tried adding exclusions as suggested but it didn't seem to help

```
$ lein deps :tree
Possibly confusing dependencies found:
[lein-cljsbuild "1.1.1"] -> [lein-cljsbuild/cljs-compat "1.0.0-SNAPSHOT"] -> [org.clojure/clojure "1.5.1"]
 overrides
[lein-figwheel "0.5.0"] -> [figwheel-sidecar "0.5.0"] -> [compojure "1.4.0"] -> [ring/ring-core "1.4.0"] -> [clj-time "0.9.0"] -> [org.clojure/clojure "1.6.0"]
 and
[lein-figwheel "0.5.0"] -> [figwheel-sidecar "0.5.0"] -> [figwheel "0.5.0"] -> [org.clojure/clojurescript "1.7.170" :exclusions [org.apache.ant/ant]] -> [org.clojure/clojure "1.7.0"]
 and
[lein-figwheel "0.5.0"] -> [figwheel "0.5.0"] -> [org.clojure/clojurescript "1.7.170" :exclusions [org.apache.ant/ant]] -> [org.clojure/clojure "1.7.0"]
 and
[lein-figwheel "0.5.0"] -> [figwheel-sidecar "0.5.0"] -> [hawk "0.2.5"] -> [org.clojure/clojure "1.6.0"]
 and
[lein-figwheel "0.5.0"] -> [figwheel-sidecar "0.5.0"] -> [figwheel "0.5.0"] -> [org.clojure/clojure "1.7.0"]
 and
[lein-figwheel "0.5.0"] -> [figwheel-sidecar "0.5.0"] -> [digest "1.4.4"] -> [org.clojure/clojure "1.6.0"]
 and
[lein-figwheel "0.5.0"] -> [figwheel-sidecar "0.5.0"] -> [ring-cors "0.1.7"] -> [org.clojure/clojure "1.6.0"]
 and
[lein-figwheel "0.5.0"] -> [figwheel-sidecar "0.5.0"] -> [org.clojure/clojurescript "1.7.170" :exclusions [org.apache.ant/ant]] -> [org.clojure/clojure "1.7.0"]
 and
[lein-figwheel "0.5.0"] -> [figwheel "0.5.0"] -> [org.clojure/clojure "1.7.0"]
 and
[lein-figwheel "0.5.0"] -> [figwheel-sidecar "0.5.0"] -> [org.clojure/clojure "1.7.0"]

Consider using these exclusions:
[lein-figwheel "0.5.0" :exclusions [org.clojure/clojure]]
[lein-figwheel "0.5.0" :exclusions [org.clojure/clojure]]
[lein-figwheel "0.5.0" :exclusions [org.clojure/clojure]]
[lein-figwheel "0.5.0" :exclusions [org.clojure/clojure]]
[lein-figwheel "0.5.0" :exclusions [org.clojure/clojure]]
[lein-figwheel "0.5.0" :exclusions [org.clojure/clojure]]
[lein-figwheel "0.5.0" :exclusions [org.clojure/clojure]]
[lein-figwheel "0.5.0" :exclusions [org.clojure/clojure]]
[lein-figwheel "0.5.0" :exclusions [org.clojure/clojure]]
[lein-figwheel "0.5.0" :exclusions [org.clojure/clojure]]

[lein-figwheel "0.5.0"] -> [figwheel-sidecar "0.5.0"] -> [ring-cors "0.1.7"] -> [ring/ring-core "1.3.2"]
 overrides
[lein-figwheel "0.5.0"] -> [figwheel-sidecar "0.5.0"] -> [compojure "1.4.0"] -> [ring/ring-core "1.4.0"]

Consider using these exclusions:
[lein-figwheel "0.5.0" :exclusions [ring/ring-core]]

[lein-figwheel "0.5.0"] -> [figwheel-sidecar "0.5.0"] -> [ring-cors "0.1.7"] -> [ring/ring-core "1.3.2"] -> [commons-fileupload "1.3"]
 overrides
[lein-figwheel "0.5.0"] -> [figwheel-sidecar "0.5.0"] -> [compojure "1.4.0"] -> [ring/ring-core "1.4.0"] -> [commons-fileupload "1.3.1"]

Consider using these exclusions:
[lein-figwheel "0.5.0" :exclusions [commons-fileupload]]

[lein-figwheel "0.5.0"] -> [figwheel-sidecar "0.5.0"] -> [ring-cors "0.1.7"] -> [ring/ring-core "1.3.2"] -> [clj-time "0.6.0"]
 overrides
[lein-figwheel "0.5.0"] -> [figwheel-sidecar "0.5.0"] -> [compojure "1.4.0"] -> [ring/ring-core "1.4.0"] -> [clj-time "0.9.0"]

Consider using these exclusions:
[lein-figwheel "0.5.0" :exclusions [clj-time]]

[lein-figwheel "0.5.0"] -> [figwheel-sidecar "0.5.0"] -> [ring-cors "0.1.7"] -> [ring/ring-core "1.3.2"] -> [clj-time "0.6.0"] -> [joda-time "2.2"]
 overrides
[lein-figwheel "0.5.0"] -> [figwheel-sidecar "0.5.0"] -> [compojure "1.4.0"] -> [ring/ring-core "1.4.0"] -> [clj-time "0.9.0"] -> [joda-time "2.6"]

Consider using these exclusions:
[lein-figwheel "0.5.0" :exclusions [joda-time]]

 [clojure-complete "0.2.3" :scope "test" :exclusions [[org.clojure/clojure]]]
 [org.clojure/clojure "1.7.0"]
 [org.clojure/clojurescript "1.7.170"]
   [com.google.javascript/closure-compiler "v20151015"]
   [org.clojure/data.json "0.2.6"]
   [org.clojure/google-closure-library "0.0-20151016-61277aea"]
     [org.clojure/google-closure-library-third-party "0.0-20151016-61277aea"]
   [org.clojure/tools.reader "0.10.0-alpha3"]
   [org.mozilla/rhino "1.7R5"]
 [org.clojure/core.async "0.2.371"]
   [org.clojure/tools.analyzer.jvm "0.6.7"]
     [org.clojure/core.memoize "0.5.6"]
       [org.clojure/core.cache "0.6.3"]
         [org.clojure/data.priority-map "0.0.2"]
     [org.clojure/tools.analyzer "0.6.6"]
     [org.ow2.asm/asm-all "4.2"]
 [org.clojure/tools.nrepl "0.2.6" :scope "test" :exclusions [[org.clojure/clojure]]]

```

**Comment by cddr** [comment]
Closing as I cannot reproduce this after upgrading my version of lein.

**Comment by eagleflo** [comment]
I just encountered this problem. Upgrading Leiningen from 2.5.1 to 2.5.3 fixed it for me as well.

**Comment by joakin** [comment]
Thanks @cddr and @eagleflo, this solved it for me too.

**Comment by tf0054** [comment]
Thank you @eagleflo, my case was on the same version issue and solved.

**Comment by sp3ctum** [comment]
More :heart:, solved my problem too. Thanks, guys!

**Comment by logaan** [comment]
Thanks everyone.

    brew upgrade leiningen

Did the trick for me.

**Comment by theikkila** [comment]
Thanks everyone.
In my project I was upgrading packages but after that couldn't start figwheel.
Updating to latest leiningen AND cljsbuild helped.

**Comment by crsmithdev** [comment]
FYI I'm seeing this exact issue, but am using leiningen 2.5.3 and lein-cljsbuild 1.1.2:

Project:
```
:dependencies [[org.clojure/clojure "1.6.0"]
                           [ring "1.3.1"]
                           [ring/ring-defaults "0.1.2"]
                           [ring/ring-json "0.3.1"]
                           [http-kit "2.1.16"]
                           [compojure "1.1.9"]
                           [com.cemerick/friend "0.2.1"]
                           [clj-time "0.8.0"]
                           [selmer "0.7.1"]
                           [org.clojure/clojurescript "1.7.170"]
                           [om "0.7.3"]
                           [figwheel "0.5.0-2"]]

            :plugins [[lein-cljsbuild "1.1.2"]
                           [org.clojure/clojurescript "1.7.170"] 
                           [lein-figwheel "0.5.0-2"]]
```

Leiningen:
```
$ lein -v
Leiningen 2.5.3 on Java 1.7.0_60 Java HotSpot(TM) 64-Bit Server VM
```

Result:
```
$ lein figwheel
Exception in thread "main" java.io.FileNotFoundException: Could not locate cljs/analyzer__init.class or cljs/analyzer.clj on classpath: , compiling:(figwheel_sidecar/utils.clj:1:1)
	at clojure.lang.Compiler.load(Compiler.java:7142)
	at clojure.lang.RT.loadResourceScript(RT.java:370)
	at clojure.lang.RT.loadResourceScript(RT.java:361)
	at clojure.lang.RT.load(RT.java:440)
	at clojure.lang.RT.load(RT.java:411)
	at clojure.core$load$fn__5066.invoke(core.clj:5641)
	at clojure.core$load.doInvoke(core.clj:5640)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invoke(core.clj:5446)
	at clojure.core$load_lib$fn__5015.invoke(core.clj:5486)
	at clojure.core$load_lib.doInvoke(core.clj:5485)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invoke(core.clj:626)
	at clojure.core$load_libs.doInvoke(core.clj:5524)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invoke(core.clj:626)
	at clojure.core$require.doInvoke(core.clj:5607)
	at clojure.lang.RestFn.invoke(RestFn.java:1289)
	at figwheel_sidecar.system$eval15$loading__4958__auto____16.invoke(system.clj:1)
	at figwheel_sidecar.system$eval15.invoke(system.clj:1)
        ....
```

**Comment by bhauman** [comment]
You definitely need clojure 1.7.0 for ClojureScript and figwheel. You probably also need to do a lein clean

**Comment by sfnelson** [comment]
This is definitely still a problem.

Using leiningen 2.5.3, clojure 1.8.0, clojurescript 1.7.228.

```
Caused by: java.io.FileNotFoundException: Could not locate cljs/analyzer__init.class or cljs/analyzer.clj on classpath.
 at clojure.lang.RT.load (RT.java:449)
    clojure.lang.RT.load (RT.java:412)
    clojure.core$load$fn__5448.invoke (core.clj:5866)
    clojure.core$load.doInvoke (core.clj:5865)
    clojure.lang.RestFn.invoke (RestFn.java:408)
    clojure.core$load_one.invoke (core.clj:5671)
    clojure.core$load_lib$fn__5397.invoke (core.clj:5711)
    clojure.core$load_lib.doInvoke (core.clj:5710)
    clojure.lang.RestFn.applyTo (RestFn.java:142)
    clojure.core$apply.invoke (core.clj:632)
    clojure.core$load_libs.doInvoke (core.clj:5749)
    clojure.lang.RestFn.applyTo (RestFn.java:137)
    clojure.core$apply.invoke (core.clj:632)
    clojure.core$require.doInvoke (core.clj:5832)
    clojure.lang.RestFn.invoke (RestFn.java:457)
    figwheel_sidecar.utils$eval660$loading__5340__auto____661.invoke (utils.clj:1)
    figwheel_sidecar.utils$eval660.invoke (utils.clj:1)
    clojure.lang.Compiler.eval (Compiler.java:6782)
```

Note that the actual file distributed by clojurescript is `cljs/analyzer.cljc` not `clj`.

**Comment by sfnelson** [comment]
In my case, the problem was caused by excluding `org.clojure/clojurescript` from the figwheel plugin import. We were doing this because figwheel depends on an explicit version of clojurescript which is not the one we want to use, but the consequence was that clojurescript was not available on the class path when the plugin started. This behaviour seems to have changed in a recent figwheel (possibly :eval-in-leiningen related?).

The workaround for us is to continue to specify our exclusion, but add `clojurescript` as a plugin.

**Comment by mharju** [comment]
I also got this error but it resolved when when I updated my Leiningen to the most recent version, 2.5.3. I also changed the dependency of `lein-cljsbuild` to `1.1.2` but I am not sure this if is required or not.

**Comment by evandrix** [comment]
I also received this error, but it was resolved when Leiningen was updated to the most recent v2.5.3.

**Comment by bhauman** [comment]
Well I shouldn't have closed this issue because this has obviously been a problem for people.  I have just released 0.5.0-4 that has hopefully eliminated the problems emanating from figwheel.

**Comment by Reefersleep** [comment]
I had this problem, only I discovered using the reagent template and reported it there; https://github.com/reagent-project/reagent-template/issues/106#issuecomment-173932999

I just saw your comment re: 0.5.0-4, @bhauman, and I tried doing 
```
lein new figwheel foobar
cd foobar
lein clean
lein figwheel
```
(And made sure that it was 0.5.0-4 in the project.clj)

And I still get
```
clojure.lang.Compiler$CompilerException: java.io.FileNotFoundException: Could not locate cljs/analyzer__init.class or cljs/analyzer.clj on classpath: , compiling:(figwheel_sidecar/utils.clj:1:1)
 at clojure.lang.Compiler.load (Compiler.java:7142)
    clojure.lang.RT.loadResourceScript (RT.java:370)
    clojure.lang.RT.loadResourceScript (RT.java:361)
    clojure.lang.RT.load (RT.java:440)
    clojure.lang.RT.load (RT.java:411)
    clojure.core$load$fn__5066.invoke (core.clj:5641)
    clojure.core$load.doInvoke (core.clj:5640)
    clojure.lang.RestFn.invoke (RestFn.java:408)
    clojure.core$load_one.invoke (core.clj:5446)
    clojure.core$load_lib$fn__5015.invoke (core.clj:5486)
    clojure.core$load_lib.doInvoke (core.clj:5485)
    clojure.lang.RestFn.applyTo (RestFn.java:142)
    clojure.core$apply.invoke (core.clj:626)
    clojure.core$load_libs.doInvoke (core.clj:5524)
    clojure.lang.RestFn.applyTo (RestFn.java:137)
    clojure.core$apply.invoke (core.clj:626)
    clojure.core$require.doInvoke (core.clj:5607)
    clojure.lang.RestFn.invoke (RestFn.java:551)
    figwheel_sidecar.config$eval651$loading__4958__auto____652.invoke (config.clj:1)
    figwheel_sidecar.config$eval651.invoke (config.clj:1)
    clojure.lang.Compiler.eval (Compiler.java:6703)
    clojure.lang.Compiler.eval (Compiler.java:6692)
    clojure.lang.Compiler.load (Compiler.java:7130)
    clojure.lang.RT.loadResourceScript (RT.java:370)
    clojure.lang.RT.loadResourceScript (RT.java:361)
    clojure.lang.RT.load (RT.java:440)
    clojure.lang.RT.load (RT.java:411)
    clojure.core$load$fn__5066.invoke (core.clj:5641)
    clojure.core$load.doInvoke (core.clj:5640)
    clojure.lang.RestFn.invoke (RestFn.java:408)
    clojure.core$load_one.invoke (core.clj:5446)
    clojure.core$load_lib$fn__5015.invoke (core.clj:5486)
    clojure.core$load_lib.doInvoke (core.clj:5485)
    clojure.lang.RestFn.applyTo (RestFn.java:142)
    clojure.core$apply.invoke (core.clj:626)
    clojure.core$load_libs.doInvoke (core.clj:5524)
    clojure.lang.RestFn.applyTo (RestFn.java:137)
    clojure.core$apply.invoke (core.clj:626)
    clojure.core$require.doInvoke (core.clj:5607)
    clojure.lang.RestFn.invoke (RestFn.java:457)
    leiningen.figwheel$eval602$loading__4958__auto____603.invoke (figwheel.clj:1)
    leiningen.figwheel$eval602.invoke (figwheel.clj:1)
    clojure.lang.Compiler.eval (Compiler.java:6703)
    clojure.lang.Compiler.eval (Compiler.java:6692)
    clojure.lang.Compiler.load (Compiler.java:7130)
    clojure.lang.RT.loadResourceScript (RT.java:370)
    clojure.lang.RT.loadResourceScript (RT.java:361)
    clojure.lang.RT.load (RT.java:440)
    clojure.lang.RT.load (RT.java:411)
    clojure.core$load$fn__5066.invoke (core.clj:5641)
    clojure.core$load.doInvoke (core.clj:5640)
    clojure.lang.RestFn.invoke (RestFn.java:408)
    clojure.core$load_one.invoke (core.clj:5446)
    clojure.core$load_lib$fn__5015.invoke (core.clj:5486)
    clojure.core$load_lib.doInvoke (core.clj:5485)
    clojure.lang.RestFn.applyTo (RestFn.java:142)
    clojure.core$apply.invoke (core.clj:626)
    clojure.core$load_libs.doInvoke (core.clj:5524)
    clojure.lang.RestFn.applyTo (RestFn.java:137)
    clojure.core$apply.invoke (core.clj:626)
    clojure.core$require.doInvoke (core.clj:5607)
    clojure.lang.RestFn.invoke (RestFn.java:408)
    leiningen.core.utils$require_resolve.invoke (utils.clj:68)
    leiningen.core.utils$require_resolve.invoke (utils.clj:71)
    leiningen.core.main$lookup_task_var.invoke (main.clj:61)
    leiningen.core.main$pass_through_help_QMARK_.invoke (main.clj:68)
    leiningen.core.main$task_args.invoke (main.clj:71)
    leiningen.core.main$resolve_and_apply.invoke (main.clj:308)
    leiningen.core.main$_main$fn__6136.invoke (main.clj:377)
    leiningen.core.main$_main.doInvoke (main.clj:366)
    clojure.lang.RestFn.invoke (RestFn.java:408)
    clojure.lang.Var.invoke (Var.java:379)
    clojure.lang.AFn.applyToHelper (AFn.java:154)
    clojure.lang.Var.applyTo (Var.java:700)
    clojure.core$apply.invoke (core.clj:624)
    clojure.main$main_opt.invoke (main.clj:315)
    clojure.main$main.doInvoke (main.clj:420)
    clojure.lang.RestFn.invoke (RestFn.java:436)
    clojure.lang.Var.invoke (Var.java:388)
    clojure.lang.AFn.applyToHelper (AFn.java:160)
    clojure.lang.Var.applyTo (Var.java:700)
    clojure.main.main (main.java:37)
Caused by: java.io.FileNotFoundException: Could not locate cljs/analyzer__init.class or cljs/analyzer.clj on classpath:
 at clojure.lang.RT.load (RT.java:443)
    clojure.lang.RT.load (RT.java:411)
    clojure.core$load$fn__5066.invoke (core.clj:5641)
    clojure.core$load.doInvoke (core.clj:5640)
    clojure.lang.RestFn.invoke (RestFn.java:408)
    clojure.core$load_one.invoke (core.clj:5446)
    clojure.core$load_lib$fn__5015.invoke (core.clj:5486)
    clojure.core$load_lib.doInvoke (core.clj:5485)
    clojure.lang.RestFn.applyTo (RestFn.java:142)
    clojure.core$apply.invoke (core.clj:626)
    clojure.core$load_libs.doInvoke (core.clj:5524)
    clojure.lang.RestFn.applyTo (RestFn.java:137)
    clojure.core$apply.invoke (core.clj:626)
    clojure.core$require.doInvoke (core.clj:5607)
    clojure.lang.RestFn.invoke (RestFn.java:457)
    figwheel_sidecar.utils$eval657$loading__4958__auto____658.invoke (utils.clj:1)
    figwheel_sidecar.utils$eval657.invoke (utils.clj:1)
    clojure.lang.Compiler.eval (Compiler.java:6703)
    clojure.lang.Compiler.eval (Compiler.java:6692)
    clojure.lang.Compiler.load (Compiler.java:7130)
    clojure.lang.RT.loadResourceScript (RT.java:370)
    clojure.lang.RT.loadResourceScript (RT.java:361)
    clojure.lang.RT.load (RT.java:440)
    clojure.lang.RT.load (RT.java:411)
    clojure.core$load$fn__5066.invoke (core.clj:5641)
    clojure.core$load.doInvoke (core.clj:5640)
    clojure.lang.RestFn.invoke (RestFn.java:408)
    clojure.core$load_one.invoke (core.clj:5446)
    clojure.core$load_lib$fn__5015.invoke (core.clj:5486)
    clojure.core$load_lib.doInvoke (core.clj:5485)
    clojure.lang.RestFn.applyTo (RestFn.java:142)
    clojure.core$apply.invoke (core.clj:626)
    clojure.core$load_libs.doInvoke (core.clj:5524)
    clojure.lang.RestFn.applyTo (RestFn.java:137)
    clojure.core$apply.invoke (core.clj:626)
    clojure.core$require.doInvoke (core.clj:5607)
    clojure.lang.RestFn.invoke (RestFn.java:551)
    figwheel_sidecar.config$eval651$loading__4958__auto____652.invoke (config.clj:1)
    figwheel_sidecar.config$eval651.invoke (config.clj:1)
    clojure.lang.Compiler.eval (Compiler.java:6703)
    clojure.lang.Compiler.eval (Compiler.java:6692)
    clojure.lang.Compiler.load (Compiler.java:7130)
    clojure.lang.RT.loadResourceScript (RT.java:370)
    clojure.lang.RT.loadResourceScript (RT.java:361)
    clojure.lang.RT.load (RT.java:440)
    clojure.lang.RT.load (RT.java:411)
    clojure.core$load$fn__5066.invoke (core.clj:5641)
    clojure.core$load.doInvoke (core.clj:5640)
    clojure.lang.RestFn.invoke (RestFn.java:408)
    clojure.core$load_one.invoke (core.clj:5446)
    clojure.core$load_lib$fn__5015.invoke (core.clj:5486)
    clojure.core$load_lib.doInvoke (core.clj:5485)
    clojure.lang.RestFn.applyTo (RestFn.java:142)
    clojure.core$apply.invoke (core.clj:626)
    clojure.core$load_libs.doInvoke (core.clj:5524)
    clojure.lang.RestFn.applyTo (RestFn.java:137)
    clojure.core$apply.invoke (core.clj:626)
    clojure.core$require.doInvoke (core.clj:5607)
    clojure.lang.RestFn.invoke (RestFn.java:457)
    leiningen.figwheel$eval602$loading__4958__auto____603.invoke (figwheel.clj:1)
    leiningen.figwheel$eval602.invoke (figwheel.clj:1)
    clojure.lang.Compiler.eval (Compiler.java:6703)
    clojure.lang.Compiler.eval (Compiler.java:6692)
    clojure.lang.Compiler.load (Compiler.java:7130)
    clojure.lang.RT.loadResourceScript (RT.java:370)
    clojure.lang.RT.loadResourceScript (RT.java:361)
    clojure.lang.RT.load (RT.java:440)
    clojure.lang.RT.load (RT.java:411)
    clojure.core$load$fn__5066.invoke (core.clj:5641)
    clojure.core$load.doInvoke (core.clj:5640)
    clojure.lang.RestFn.invoke (RestFn.java:408)
    clojure.core$load_one.invoke (core.clj:5446)
    clojure.core$load_lib$fn__5015.invoke (core.clj:5486)
    clojure.core$load_lib.doInvoke (core.clj:5485)
    clojure.lang.RestFn.applyTo (RestFn.java:142)
    clojure.core$apply.invoke (core.clj:626)
    clojure.core$load_libs.doInvoke (core.clj:5524)
    clojure.lang.RestFn.applyTo (RestFn.java:137)
    clojure.core$apply.invoke (core.clj:626)
    clojure.core$require.doInvoke (core.clj:5607)
    clojure.lang.RestFn.invoke (RestFn.java:408)
    leiningen.core.utils$require_resolve.invoke (utils.clj:68)
    leiningen.core.utils$require_resolve.invoke (utils.clj:71)
    leiningen.core.main$lookup_task_var.invoke (main.clj:61)
    leiningen.core.main$pass_through_help_QMARK_.invoke (main.clj:68)
    leiningen.core.main$task_args.invoke (main.clj:71)
    leiningen.core.main$resolve_and_apply.invoke (main.clj:308)
    leiningen.core.main$_main$fn__6136.invoke (main.clj:377)
    leiningen.core.main$_main.doInvoke (main.clj:366)
    clojure.lang.RestFn.invoke (RestFn.java:408)
    clojure.lang.Var.invoke (Var.java:379)
    clojure.lang.AFn.applyToHelper (AFn.java:154)
    clojure.lang.Var.applyTo (Var.java:700)
    clojure.core$apply.invoke (core.clj:624)
    clojure.main$main_opt.invoke (main.clj:315)
    clojure.main$main.doInvoke (main.clj:420)
    clojure.lang.RestFn.invoke (RestFn.java:436)
    clojure.lang.Var.invoke (Var.java:388)
    clojure.lang.AFn.applyToHelper (AFn.java:160)
    clojure.lang.Var.applyTo (Var.java:700)
    clojure.main.main (main.java:37)
```

**Comment by bhauman** [comment]
@Reefersleep I'm going to fix this today. 

What causes this is Clojure 1.6 trying interacting with the Clojure 1.7 codebase in ClojureScript. This is  happening in the Leiningen process.

More than likely you have a profiles.clj and some plugin is bringing in Clojure 1.6 into the Leiningen process.

If you do a lein deps :tree 

and a lein deps :plugin-tree

You should see something that indicates that this is the case.

I'm going to try and remove references to Clojure 1.7 code in the plugin. And this should smooth the road for folks in the future.

**Comment by bhauman** [comment]
@Reefersleep
Pushed a new version of figwheel 0.5.0-5

Would appreciate feedback.

**Comment by Reefersleep** [comment]
Speedy, @bhauman! :)

I tried `lein new figwheel foobar` and checked the project.clj to make sure that it used 0.5.0-5, then did `lein figwheel`, resulting in the following stacktrace:
```
Retrieving lein-figwheel/lein-figwheel/0.5.0-5/lein-figwheel-0.5.0-5.pom from clojars
Retrieving figwheel-sidecar/figwheel-sidecar/0.5.0-5/figwheel-sidecar-0.5.0-5.pom from clojars
Retrieving figwheel/figwheel/0.5.0-5/figwheel-0.5.0-5.pom from clojars
Retrieving hawk/hawk/0.2.9/hawk-0.2.9.pom from clojars
Retrieving lein-figwheel/lein-figwheel/0.5.0-5/lein-figwheel-0.5.0-5.jar from clojars
Retrieving hawk/hawk/0.2.9/hawk-0.2.9.jar from clojars
Retrieving figwheel/figwheel/0.5.0-5/figwheel-0.5.0-5.jar from clojars
Retrieving figwheel-sidecar/figwheel-sidecar/0.5.0-5/figwheel-sidecar-0.5.0-5.jar from clojars
clojure.lang.Compiler$CompilerException: java.lang.RuntimeException: Unable to resolve symbol: update in this context, compiling:(figwheel_sidecar/config.clj:66:5)
 at clojure.lang.Compiler.analyze (Compiler.java:6464)
    clojure.lang.Compiler.analyze (Compiler.java:6406)
    clojure.lang.Compiler$InvokeExpr.parse (Compiler.java:3665)
    clojure.lang.Compiler.analyzeSeq (Compiler.java:6646)
    clojure.lang.Compiler.analyze (Compiler.java:6445)
    clojure.lang.Compiler.analyze (Compiler.java:6406)
    clojure.lang.Compiler$IfExpr$Parser.parse (Compiler.java:2708)
    clojure.lang.Compiler.analyzeSeq (Compiler.java:6644)
    clojure.lang.Compiler.analyze (Compiler.java:6445)
    clojure.lang.Compiler.analyze (Compiler.java:6406)
    clojure.lang.Compiler$BodyExpr$Parser.parse (Compiler.java:5782)
    clojure.lang.Compiler$LetExpr$Parser.parse (Compiler.java:6100)
    clojure.lang.Compiler.analyzeSeq (Compiler.java:6644)
    clojure.lang.Compiler.analyze (Compiler.java:6445)
    clojure.lang.Compiler.analyzeSeq (Compiler.java:6632)
    clojure.lang.Compiler.analyze (Compiler.java:6445)
    clojure.lang.Compiler.analyze (Compiler.java:6406)
    clojure.lang.Compiler$BodyExpr$Parser.parse (Compiler.java:5782)
    clojure.lang.Compiler$FnMethod.parse (Compiler.java:5217)
    clojure.lang.Compiler$FnExpr.parse (Compiler.java:3846)
    clojure.lang.Compiler.analyzeSeq (Compiler.java:6642)
    clojure.lang.Compiler.analyze (Compiler.java:6445)
    clojure.lang.Compiler.analyzeSeq (Compiler.java:6632)
    clojure.lang.Compiler.analyze (Compiler.java:6445)
    clojure.lang.Compiler.access$100 (Compiler.java:38)
    clojure.lang.Compiler$DefExpr$Parser.parse (Compiler.java:538)
    clojure.lang.Compiler.analyzeSeq (Compiler.java:6644)
    clojure.lang.Compiler.analyze (Compiler.java:6445)
    clojure.lang.Compiler.analyze (Compiler.java:6406)
    clojure.lang.Compiler.eval (Compiler.java:6707)
    clojure.lang.Compiler.load (Compiler.java:7130)
    clojure.lang.RT.loadResourceScript (RT.java:370)
    clojure.lang.RT.loadResourceScript (RT.java:361)
    clojure.lang.RT.load (RT.java:440)
    clojure.lang.RT.load (RT.java:411)
    clojure.core$load$fn__5066.invoke (core.clj:5641)
    clojure.core$load.doInvoke (core.clj:5640)
    clojure.lang.RestFn.invoke (RestFn.java:408)
    clojure.core$load_one.invoke (core.clj:5446)
    clojure.core$load_lib$fn__5015.invoke (core.clj:5486)
    clojure.core$load_lib.doInvoke (core.clj:5485)
    clojure.lang.RestFn.applyTo (RestFn.java:142)
    clojure.core$apply.invoke (core.clj:626)
    clojure.core$load_libs.doInvoke (core.clj:5524)
    clojure.lang.RestFn.applyTo (RestFn.java:137)
    clojure.core$apply.invoke (core.clj:626)
    clojure.core$require.doInvoke (core.clj:5607)
    clojure.lang.RestFn.invoke (RestFn.java:457)
    leiningen.figwheel$eval602$loading__4958__auto____603.invoke (figwheel.clj:1)
    leiningen.figwheel$eval602.invoke (figwheel.clj:1)
    clojure.lang.Compiler.eval (Compiler.java:6703)
    clojure.lang.Compiler.eval (Compiler.java:6692)
    clojure.lang.Compiler.load (Compiler.java:7130)
    clojure.lang.RT.loadResourceScript (RT.java:370)
    clojure.lang.RT.loadResourceScript (RT.java:361)
    clojure.lang.RT.load (RT.java:440)
    clojure.lang.RT.load (RT.java:411)
    clojure.core$load$fn__5066.invoke (core.clj:5641)
    clojure.core$load.doInvoke (core.clj:5640)
    clojure.lang.RestFn.invoke (RestFn.java:408)
    clojure.core$load_one.invoke (core.clj:5446)
    clojure.core$load_lib$fn__5015.invoke (core.clj:5486)
    clojure.core$load_lib.doInvoke (core.clj:5485)
    clojure.lang.RestFn.applyTo (RestFn.java:142)
    clojure.core$apply.invoke (core.clj:626)
    clojure.core$load_libs.doInvoke (core.clj:5524)
    clojure.lang.RestFn.applyTo (RestFn.java:137)
    clojure.core$apply.invoke (core.clj:626)
    clojure.core$require.doInvoke (core.clj:5607)
    clojure.lang.RestFn.invoke (RestFn.java:408)
    leiningen.core.utils$require_resolve.invoke (utils.clj:68)
    leiningen.core.utils$require_resolve.invoke (utils.clj:71)
    leiningen.core.main$lookup_task_var.invoke (main.clj:61)
    leiningen.core.main$pass_through_help_QMARK_.invoke (main.clj:68)
    leiningen.core.main$task_args.invoke (main.clj:71)
    leiningen.core.main$resolve_and_apply.invoke (main.clj:308)
    leiningen.core.main$_main$fn__6136.invoke (main.clj:377)
    leiningen.core.main$_main.doInvoke (main.clj:366)
    clojure.lang.RestFn.invoke (RestFn.java:408)
    clojure.lang.Var.invoke (Var.java:379)
    clojure.lang.AFn.applyToHelper (AFn.java:154)
    clojure.lang.Var.applyTo (Var.java:700)
    clojure.core$apply.invoke (core.clj:624)
    clojure.main$main_opt.invoke (main.clj:315)
    clojure.main$main.doInvoke (main.clj:420)
    clojure.lang.RestFn.invoke (RestFn.java:436)
    clojure.lang.Var.invoke (Var.java:388)
    clojure.lang.AFn.applyToHelper (AFn.java:160)
    clojure.lang.Var.applyTo (Var.java:700)
    clojure.main.main (main.java:37)
Caused by: java.lang.RuntimeException: Unable to resolve symbol: update in this context
 at clojure.lang.Util.runtimeException (Util.java:221)
    clojure.lang.Compiler.resolveIn (Compiler.java:6940)
    clojure.lang.Compiler.resolve (Compiler.java:6884)
    clojure.lang.Compiler.analyzeSymbol (Compiler.java:6845)
    clojure.lang.Compiler.analyze (Compiler.java:6427)
    clojure.lang.Compiler.analyze (Compiler.java:6406)
    clojure.lang.Compiler$InvokeExpr.parse (Compiler.java:3665)
    clojure.lang.Compiler.analyzeSeq (Compiler.java:6646)
    clojure.lang.Compiler.analyze (Compiler.java:6445)
    clojure.lang.Compiler.analyze (Compiler.java:6406)
    clojure.lang.Compiler$IfExpr$Parser.parse (Compiler.java:2708)
    clojure.lang.Compiler.analyzeSeq (Compiler.java:6644)
    clojure.lang.Compiler.analyze (Compiler.java:6445)
    clojure.lang.Compiler.analyze (Compiler.java:6406)
    clojure.lang.Compiler$BodyExpr$Parser.parse (Compiler.java:5782)
    clojure.lang.Compiler$LetExpr$Parser.parse (Compiler.java:6100)
    clojure.lang.Compiler.analyzeSeq (Compiler.java:6644)
    clojure.lang.Compiler.analyze (Compiler.java:6445)
    clojure.lang.Compiler.analyzeSeq (Compiler.java:6632)
    clojure.lang.Compiler.analyze (Compiler.java:6445)
    clojure.lang.Compiler.analyze (Compiler.java:6406)
    clojure.lang.Compiler$BodyExpr$Parser.parse (Compiler.java:5782)
    clojure.lang.Compiler$FnMethod.parse (Compiler.java:5217)
    clojure.lang.Compiler$FnExpr.parse (Compiler.java:3846)
    clojure.lang.Compiler.analyzeSeq (Compiler.java:6642)
    clojure.lang.Compiler.analyze (Compiler.java:6445)
    clojure.lang.Compiler.analyzeSeq (Compiler.java:6632)
    clojure.lang.Compiler.analyze (Compiler.java:6445)
    clojure.lang.Compiler.access$100 (Compiler.java:38)
    clojure.lang.Compiler$DefExpr$Parser.parse (Compiler.java:538)
    clojure.lang.Compiler.analyzeSeq (Compiler.java:6644)
    clojure.lang.Compiler.analyze (Compiler.java:6445)
    clojure.lang.Compiler.analyze (Compiler.java:6406)
    clojure.lang.Compiler.eval (Compiler.java:6707)
    clojure.lang.Compiler.load (Compiler.java:7130)
    clojure.lang.RT.loadResourceScript (RT.java:370)
    clojure.lang.RT.loadResourceScript (RT.java:361)
    clojure.lang.RT.load (RT.java:440)
    clojure.lang.RT.load (RT.java:411)
    clojure.core$load$fn__5066.invoke (core.clj:5641)
    clojure.core$load.doInvoke (core.clj:5640)
    clojure.lang.RestFn.invoke (RestFn.java:408)
    clojure.core$load_one.invoke (core.clj:5446)
    clojure.core$load_lib$fn__5015.invoke (core.clj:5486)
    clojure.core$load_lib.doInvoke (core.clj:5485)
    clojure.lang.RestFn.applyTo (RestFn.java:142)
    clojure.core$apply.invoke (core.clj:626)
    clojure.core$load_libs.doInvoke (core.clj:5524)
    clojure.lang.RestFn.applyTo (RestFn.java:137)
    clojure.core$apply.invoke (core.clj:626)
    clojure.core$require.doInvoke (core.clj:5607)
    clojure.lang.RestFn.invoke (RestFn.java:457)
    leiningen.figwheel$eval602$loading__4958__auto____603.invoke (figwheel.clj:1)
    leiningen.figwheel$eval602.invoke (figwheel.clj:1)
    clojure.lang.Compiler.eval (Compiler.java:6703)
    clojure.lang.Compiler.eval (Compiler.java:6692)
    clojure.lang.Compiler.load (Compiler.java:7130)
    clojure.lang.RT.loadResourceScript (RT.java:370)
    clojure.lang.RT.loadResourceScript (RT.java:361)
    clojure.lang.RT.load (RT.java:440)
    clojure.lang.RT.load (RT.java:411)
    clojure.core$load$fn__5066.invoke (core.clj:5641)
    clojure.core$load.doInvoke (core.clj:5640)
    clojure.lang.RestFn.invoke (RestFn.java:408)
    clojure.core$load_one.invoke (core.clj:5446)
    clojure.core$load_lib$fn__5015.invoke (core.clj:5486)
    clojure.core$load_lib.doInvoke (core.clj:5485)
    clojure.lang.RestFn.applyTo (RestFn.java:142)
    clojure.core$apply.invoke (core.clj:626)
    clojure.core$load_libs.doInvoke (core.clj:5524)
    clojure.lang.RestFn.applyTo (RestFn.java:137)
    clojure.core$apply.invoke (core.clj:626)
    clojure.core$require.doInvoke (core.clj:5607)
    clojure.lang.RestFn.invoke (RestFn.java:408)
    leiningen.core.utils$require_resolve.invoke (utils.clj:68)
    leiningen.core.utils$require_resolve.invoke (utils.clj:71)
    leiningen.core.main$lookup_task_var.invoke (main.clj:61)
    leiningen.core.main$pass_through_help_QMARK_.invoke (main.clj:68)
    leiningen.core.main$task_args.invoke (main.clj:71)
    leiningen.core.main$resolve_and_apply.invoke (main.clj:308)
    leiningen.core.main$_main$fn__6136.invoke (main.clj:377)
    leiningen.core.main$_main.doInvoke (main.clj:366)
    clojure.lang.RestFn.invoke (RestFn.java:408)
    clojure.lang.Var.invoke (Var.java:379)
    clojure.lang.AFn.applyToHelper (AFn.java:154)
    clojure.lang.Var.applyTo (Var.java:700)
    clojure.core$apply.invoke (core.clj:624)
    clojure.main$main_opt.invoke (main.clj:315)
    clojure.main$main.doInvoke (main.clj:420)
    clojure.lang.RestFn.invoke (RestFn.java:436)
    clojure.lang.Var.invoke (Var.java:388)
    clojure.lang.AFn.applyToHelper (AFn.java:160)
    clojure.lang.Var.applyTo (Var.java:700)
    clojure.main.main (main.java:37)
```

**Comment by Reefersleep** [comment]
I deliberately emptied my ~/.lein/profiles.clj before any of my `lein new figwheel <name>` attempts: 
```
{:user {:plugins []
        :dependencies []}}
``` 
As far as I can tell, there are no references to Clojure 1.6 here:
```
c:\dev\clojure\Projects\foobar>lein deps :tree
warn
 [clojure-complete "0.2.3" :scope "test" :exclusions [[org.clojure/clojure]]]
 [org.clojure/clojure "1.7.0"]
 [org.clojure/clojurescript "1.7.170"]
   [com.google.javascript/closure-compiler "v20151015"]
   [org.clojure/data.json "0.2.6"]
   [org.clojure/google-closure-library "0.0-20151016-61277aea"]
     [org.clojure/google-closure-library-third-party "0.0-20151016-61277aea"]
   [org.clojure/tools.reader "0.10.0-alpha3"]
   [org.mozilla/rhino "1.7R5"]
 [org.clojure/core.async "0.2.374" :exclusions [[org.clojure/tools.reader]]]
   [org.clojure/tools.analyzer.jvm "0.6.9"]
     [org.clojure/core.memoize "0.5.8"]
       [org.clojure/core.cache "0.6.4"]
         [org.clojure/data.priority-map "0.0.4"]
     [org.clojure/tools.analyzer "0.6.7"]
     [org.ow2.asm/asm-all "4.2"]
 [org.clojure/tools.nrepl "0.2.6" :scope "test" :exclusions [[org.clojure/clojure]]]
```

and here:

```
c:\dev\clojure\Projects\foobar>lein deps :plugin-tree
warn
 [lein-cljsbuild "1.1.2" :exclusions [[org.clojure/clojure]]]
   [fs "1.1.2"]
     [org.apache.commons/commons-compress "1.3"]
   [lein-cljsbuild/cljs-compat "1.0.0-20151218.091126-41"]
 [lein-figwheel "0.5.0-5"]
   [figwheel-sidecar "0.5.0-5"]
     [clj-stacktrace "0.2.8"]
     [com.stuartsierra/component "0.3.0"]
       [com.stuartsierra/dependency "0.2.0"]
     [compojure "1.4.0" :exclusions [[org.clojure/clojure]]]
       [clout "2.1.2"]
         [instaparse "1.4.0" :exclusions [[org.clojure/clojure]]]
       [medley "0.6.0"]
       [org.clojure/tools.macro "0.1.5"]
       [ring/ring-codec "1.0.0"]
         [commons-codec "1.6"]
       [ring/ring-core "1.4.0"]
         [clj-time "0.9.0"]
           [joda-time "2.6"]
         [commons-fileupload "1.3.1"]
         [commons-io "2.4"]
         [crypto-equality "1.0.0"]
         [crypto-random "1.2.0"]
     [digest "1.4.4" :exclusions [[org.clojure/clojure]]]
     [hawk "0.2.9" :exclusions [[org.clojure/clojure]]]
       [net.incongru.watchservice/barbary-watchservice "1.0"]
         [net.java.dev.jna/jna "3.2.2"]
     [http-kit "2.1.19"]
     [org.clojure/clojure "1.7.0"]
     [org.clojure/clojurescript "1.7.170" :exclusions [[org.apache.ant/ant]]]
       [com.google.javascript/closure-compiler "v20151015"]
       [org.clojure/data.json "0.2.6"]
       [org.clojure/google-closure-library "0.0-20151016-61277aea"]
         [org.clojure/google-closure-library-third-party "0.0-20151016-61277aea"]
       [org.clojure/tools.reader "0.10.0-alpha3"]
       [org.mozilla/rhino "1.7R5"]
     [org.clojure/core.async "0.2.374" :exclusions [[org.clojure/tools.reader]]]
       [org.clojure/tools.analyzer.jvm "0.6.9"]
         [org.clojure/core.memoize "0.5.8"]
           [org.clojure/core.cache "0.6.4"]
             [org.clojure/data.priority-map "0.0.4"]
         [org.clojure/tools.analyzer "0.6.7"]
         [org.ow2.asm/asm-all "4.2"]
     [ring-cors "0.1.7" :exclusions [[ring/ring-core] [org.clojure/clojure]]]
   [figwheel "0.5.0-5"]
```

**Comment by Reefersleep** [comment]
I ensured that I was using lein 2.5.3 earlier, but just to make sure, I did `lein upgrade`, and `lein -version` still reports
`Leiningen 2.5.3 on Java 1.8.0_65 Java HotSpot(TM) 64-Bit Server VM`

I tried doing `lein clean` on both project/foobar and projects/last-ver, two fresh figwheel template projects using 0.5.0-5 and 0.5.0-4 respectively, before doing `lein figwheel` anew. Both still resulted in their respective errors; 
`Caused by: java.lang.RuntimeException: Unable to resolve symbol: update in this context` 
for 0.5.0-5, and 
`clojure.lang.Compiler$CompilerException: java.io.FileNotFoundException: Could not locate cljs/analyzer__init.class or cljs/analyzer.clj on classpath: , compiling:(figwheel_sidecar/utils.clj:1:1)` 
for 0.5.0-4.

My lein fu is very weak, so I don't know if there are other things I could do to "reset" my environment :/

**Comment by bhauman** [comment]
Well `clojure.core/update` was added in Clojure 1.7 so lein is still running 1.6 in its process.  

So you are on window and leinigen is insisting on using 1.6. Strange.

**Comment by bhauman** [comment]
Well run a `lein deps` first and see if that gets 1.7 into your system.

**Comment by Reefersleep** [comment]
Ran `lein deps` in both projects, got the exact same stracktraces on `lein figwheel`.

Maybe I should try to reinstall leiningen from scratch with http://leiningen-win-installer.djpowell.net/ ?

**Comment by bhauman** [comment]
Whats happening is that lein.bat 
is finding the 1.6 clojure.main on you class path and launching leiningen with it.

Please don't change anything. I'm about to release another version

**Comment by bhauman** [comment]
I want to fix this for everyone.

**Comment by bhauman** [comment]
I just released 0.5.0-6

If you could try a fresh project with and change the figwheel dep to 0.5.0-6 
I would really appreciate it.

**Comment by Reefersleep** [comment]
Great success! ^^ The appreciation is mutual :D

```
c:\dev\clojure\Projects\ip-man>lein figwheel
Retrieving lein-figwheel/lein-figwheel/0.5.0-6/lein-figwheel-0.5.0-6.pom from clojars
Retrieving figwheel-sidecar/figwheel-sidecar/0.5.0-6/figwheel-sidecar-0.5.0-6.pom from clojars
Retrieving figwheel/figwheel/0.5.0-6/figwheel-0.5.0-6.pom from clojars
Retrieving lein-figwheel/lein-figwheel/0.5.0-6/lein-figwheel-0.5.0-6.jar from clojars
Retrieving figwheel/figwheel/0.5.0-6/figwheel-0.5.0-6.jar from clojars
Retrieving figwheel-sidecar/figwheel-sidecar/0.5.0-6/figwheel-sidecar-0.5.0-6.jar from clojars
System Warning: Detected Clojure Version 1.6.0
  Figwheel requires Clojure 1.7.0 at least.
  This may only be occuring in the Leinigen (bootstrapping) process but still something to be aware of.
  Especially if this message is immediately followed by an strange stack trace.
  Check lein deps :tree or lein deps :plugin-tree for clues.
  Also, don't forget the influence of profiles.clj
Figwheel: Starting server at http://localhost:3449
Figwheel: Watching build - dev
←[0mCompiling "resources/public/js/compiled/ip_man.js" from ["src"]...
←[32mSuccessfully compiled "resources/public/js/compiled/ip_man.js" in 9.883 seconds.←[0m
Figwheel: Starting CSS Watcher for paths  ["resources/public/css"]
Launching ClojureScript REPL for build: dev
Figwheel Controls:
          (stop-autobuild)                ;; stops Figwheel autobuilder
          (start-autobuild [id ...])      ;; starts autobuilder focused on optional ids
          (switch-to-build id ...)        ;; switches autobuilder to different build
          (reset-autobuild)               ;; stops, cleans, and starts autobuilder
          (reload-config)                 ;; reloads build config and resets autobuild
          (build-once [id ...])           ;; builds source one time
          (clean-builds [id ..])          ;; deletes compiled cljs target files
          (print-config [id ...])         ;; prints out build configurations
          (fig-status)                    ;; displays current state of system
  Switch REPL build focus:
          :cljs/quit                      ;; allows you to switch REPL to another build
    Docs: (doc function-name-here)
    Exit: Control+C or :cljs/quit
 Results: Stored in vars *1, *2, *3, *e holds last exception object
Prompt will show when Figwheel connects to your application
```
Fantastic, now I can move on with my app!

Maybe I should open an issue at the Leiningen repo re: choosing Clojure 1.6 over 1.7?

**Comment by bhauman** [comment]
Great! Glad it works!  

You may want to ask the folks who are packaging lein for you.

Make sure you restore your profiles.clj

**Comment by Reefersleep** [comment]
Sure :) I got lein directly from leiningen.org, so I guess I'll make an attempt at an issue there. And I'll pass the message on to yogthos at the reagent template repo.

**Comment by kaosko** [comment]
Just for the next reader, I ended up with this issue (_Could not locate cljs/analyzer__init.class_) by doing "lein uberjar" while having a defmacro in .cljc namespace. The macro worked both in clj and cljs but I didn't really need it, so I just removed it.
